<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aerial_micro_inspection</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="sarax@todo.todo">sarax</maintainer>
  <license>TODO: License declaration</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <depend>aerial_micro_inspection_interfaces</depend>
  <exec_depend>ros_ign_gazebo</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>px4_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>ros2_yolo_interfaces</exec_depend>
  <depend>gazebo_msgs</depend>
  <depend>geographic_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
