model:
  path: '/home/sarax/det_ws/src/ai_scanner/weights/yolo11n_tree_seg_aug.pt'

input:
  camera_topic: '/zed/zed_node/left/image_rect_color'
  img_type: 'raw'

output:
  detection_topic: '/detection'
  visualization_topic: '/detection_image'


detection:
  confidence_threshold: 0.35
  iou_threshold: 0.3

visualization: true


