image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1272.39108,    0.     ,  975.91168,
            0.     , 1272.95114,  536.95711,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.008635, -0.001772, 0.001680, 0.000881, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1265.54465,    0.     ,  978.10317,    0.     ,
            0.     , 1270.98651,  538.15396,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
