
####### MESH PATHS #######
#mesh_path: "../../simulation/gazebo/worlds/Prius_clean/model_mesh.obj"
#mesh_path: "../../simulation/gazebo/worlds/Bus/bus_clean.obj"
#mesh_path: "../../simulation/gazebo/worlds/cube/meshes/cube.obj"
#mesh_path: "../../simulation/gazebo/worlds/Hunter2/Hunter2.obj"
mesh_path: "../../simulation/gazebo/worlds/Fake_Blade/Fake_blade.obj"

####### CAMERA CONFIG PATH #######
camera_config: "../../config/real_test/cameras_calib_dji_mavic2_enterprise_2x.yaml"

####### OUTPUT PATH #######
output_path: "../../config/viewpoints.yaml"

###### PLANNING CONFIG #######
planning_path: "../../config/path.yaml"

penalty_factor: 1000.0 #penalty factor for the path planner, higher values will result in more conservative paths that avoid occlusions

####### VIEWPOINT GENERATION CONFIG #######
mesh_scale: 0.001

resolution_target: 0.001 #0.0001 takes 26 min  # metres/pixel  First test 0.0006

surface_threshold: 0.7 #desired similarity between two triangle normals to be considered as the same surface

visualize: true

subdivide_edge_size: 0.05 #size of the longest edge of a triangle after subdivision, 0.05 for the Prius #0.1 for the bus

alpha: 1.0 # Reduction of the efective FOV to reduce radial distortion, 1 means no reduction, 0.8 means 20% reduction

beta: 0.9 # Reduction of the effective FOV to ensure overlap, 1 means no reduction, 0.8 means 20% reduction 

max_angle: 10.0 #maximum angle between the camera normal and the surface normal for inspection, in degrees

visualize_heatmap: false #whether to visualize the heatmap of the surface coverage


####### WELDING CONFIG #######
weld_tolerance: 0.00001 #tolerance for welding vertices

weld_mesh: true

####### FILTERS #######
plane_filter:
  ground_plane:
    enabled: true
    visualize: true
    visualize_size: 5.0         #Size of the visualized plane, in metres of the square side
    point: [0.0, 0.0, -0.1]     # For the Prius
    normal: [0.0, 0.0, 1.0]    # normal looking upwards in ENU, in NED it would be [0.0, 0.0, -1.0]
    min_distance: 0.2          # Minimum distance from the ground plane to consider a point as valid

  ceiling_plane:
    enabled: false
    visualize: true
    visualize_size: 5.0       #Size of the visualized plane, in metres of the square side
    point: [0.0, 0.0, 3.0]     # For the Prius
    normal: [0.0, 0.0, -1.0]    # normal looking downwards in ENU, in NED it would be [0.0, 0.0, 1.0]
    min_distance: 0.0          # Minimum distance from the ground plane to consider a point as valid


occlude_filter:
  enabled: true
  permessivity: 0.00 #Extra filter for fine tuning, avoids some surfaces to be deleted by mistake as the base filter is very restrictive. The Higher numebr, the more permissive it is.

interior_filter:
  enabled: true
  voxel_size: 0.1 #size of the voxels for the interior filter, in metres

filter_small_surfaces:
  enabled: true
  iqr_k: 0.3         # 1.5 for cube, 0.3 for prius
  fallback_ratio: 0.3 # only used if all surfaces happen to be the same size
  fine_tune: 0.0      # fine tune the threshold by adding a percentage of the median value, can be positive or negative, for example 0.1 will add 10% of the median value to the threshold, -0.1 will subtract 10% of the median value from the threshold
  #35 for the bus



####### REFERENCE FRAME CONFIG #######

frame_translation: [10.0, 4.0, 0.5] #translation from the obejct frame to the gps reference point, in the local frame coordiantes

latitude_reference: 47.39795305343914
longitude_reference: 8.546296503754991
altitude_reference: 0.1744191199541092

yaw_difference: 180.0 #yaw difference between object and drone frame, for ENU to NED is 90 degrees
pitch_difference: 0.0 #pitch difference between object and drone frame, normally will be 0
roll_difference: 0.0 #roll difference between object and drone frame, for ENU to NED is 180 degrees