#!/bin/sh
#
# @name Gazebo x500 inspection
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_inspection}

. ${R}etc/init.d-posix/airframes/4019_gz_x500_gimbal

param set-default MPC_XY_VEL_MAX 1.0
param set-default MPC_Z_VEL_MAX_UP 1.0
param set-default MPC_Z_VEL_MAX_DN 1.0
param set-default MPC_TILTMAX_AIR 30.0