---
input: 
  video_device:               ""                         
  nav_image_topic:            "/nav_cam/rgb_image/image_raw"
  ai_image_topic:             "/inspection_cam/rgb_image/image_raw"
  depth_image_topic:          "/nav_cam/depth_image/image_raw"
  drone_states_topic:         ""
  gimbal_orientation_topic:   "/gimbal_orientation"
  pan_tilt_calibration:       "cameras_sim.yaml"
  img_type:                   "rect"                                  

output:
  detection_topic:            "/detection"
  detection_vis_topic:        "/detection_image"
  gimbal_planning_img_topic:  "/gimbal_planning_img"
  gimbal_setpoint:            "/gimbal_reference"

detection:
  det_mode:                   "ai"                                   
  confidence_threshold: 0.27                                          
  iou_threshold: 0.3
  path: "/ws/src/ai_scanner/weights/yolo11n_tree_seg_tuned.pt"  

  min_size: 10.0
  ## Green    
  # h_min: 61
  # h_max: 104
  # s_min: 150
  # s_max: 255
  # v_min: 131
  # v_max: 255

  ## Red    
  # h_min: 0
  # h_max: 60
  # s_min: 150
  # s_max: 255
  # v_min: 200
  # v_max: 255

    # Red    
  h_min: 10
  h_max: 60
  s_min: 120
  s_max: 255
  v_min: 120
  v_max: 255

planning:
  mode: "sweeping" # Options are: pitch_lock, pitch_yaw_lock, sweeping 

gimbal:
  serial_port: "/dev/ttyTHS1"
  baudrate: 115200
  mavlink_url: "udpin:0.0.0.0:14540"

runtime:
  use_sim_time: true
  use_trt: false
  downsample_visualization: false
  visualization_width: 240
  visualization_height: 160

visualization: true                                                
...